/** 成就定义、统计条件与奖励应用。
 * 初始化由 runtime/index.js 统一协调；字段与原符号映射见 docs/symbol-map.json。
 */
import { POINT_EVENT_DUNGEON_CLEARED, POINT_EVENT_ENCOUNTER, POINT_EVENT_LEVEL_CLEARED, increasePointEventReward, pointEventsById } from "./points.js";
import { game } from "../runtime/game.js";
import { recordGameEvent } from "../core/math.js";
import { getClassVictories, getSoloClassVictories } from "./statistics.js";
import { getPartyMaxLevel } from "../characters/party.js";
export var achievementDefinitions;
export function Achievement(a) {
  this.Of = this.We = false;
  this.id = a.id;
  this.name = a.name;
  this.requirementType = a.requirementType;
  this.requiredCount = a.requiredCount;
  this.characterClass = a.characterClass;
  this.pointEventTypeId = a.pointEventTypeId;
  this.Vt = pointEventsById[a.pointEventTypeId].yc;
  this.isVictoryAchievement = !!a.isVictoryAchievement;
  this.Rt = this.Pt = null;
}
export function getAchievementRewardLabel(a) {
  if (!a.Pt) {
    a.Pt = "+" + a.Vt + "成就点每" + pointEventsById[a.pointEventTypeId].Fc;
  }
  return a.Pt;
}
export function getAchievementRequirementLabel(a) {
  if (!a.Rt) {
    a.Rt = describeAchievementRequirement(a);
  }
  return a.Rt;
}
export function applyAchievementReward(a) {
  if (!a.We || a.Of) {
    console.log("not applying achievement bonus. obtained=" + a.We + " applied=" + a.Of);
  } else {
    increasePointEventReward(a.pointEventTypeId, a.Vt);
    a.Of = true;
    var b = game.state.achievements,
      c = b.Ze.indexOf(a);
    if (-1 < c) {
      b.Ze.splice(c, 1);
    }
    recordGameEvent("Achievement", a.name);
  }
}
export function hasVictoryAchievement(a) {
  var b = game.state.victoryStatistics;
  switch (a.requirementType) {
    case 23:
      return 1 === a.requiredCount ? 0 < b.hn : 2 === a.requiredCount ? 0 < b.jn : 3 === a.requiredCount ? 0 < b.kn : false;
    case 24:
      return 0 < b.vn;
    case 25:
      return 0 < getClassVictories(b, a.characterClass);
    case 26:
      return b.Xm >= a.requiredCount;
    case 27:
      return 0 < getSoloClassVictories(b, a.characterClass);
    default:
      return false;
  }
}
export function getAchievementProgress(a) {
  var b = game.state.lifetimeStatistics;
  switch (a.requirementType) {
    case 1:
      return b.si;
    case 2:
      return b.Dl;
    case 3:
      return b.El;
    case 4:
      return b.ul;
    case 5:
      return b.Nl;
    case 6:
      return b.Sl;
    case 7:
      return b.tk;
    case 8:
      return b.Ph;
    case 9:
      return b.Rk;
    case 10:
      return b.dungeonsCleared;
    case 11:
      return b.castlesConquered;
    case 12:
      return b.Gl;
    case 13:
      return b.hl;
    case 14:
      return b.wl;
    case 15:
      return b.kl;
    case 16:
      return getPartyMaxLevel(game.state.party);
    case 17:
      return b.doorsOpened;
    case 18:
      return b.Gi;
    case 19:
      return b.Ol;
    case 20:
      return b.xl;
    case 21:
      return b.Zk;
    case 22:
      return b.nk;
    case 28:
      return b.minionKills;
  }
}
export function describeAchievementRequirement(a) {
  switch (a.requirementType) {
    case 1:
      return "杀点什么";
    case 2:
      return "使用更多卷轴";
    case 3:
      return "使用很多卷轴";
    case 4:
      return "嗑药";
    case 5:
      return "打开财宝箱";
    case 6:
      return "搜索武器架";
    case 7:
      return "搜索书架";
    case 8:
      return "卖出道具";
    case 9:
      return "购买农场";
    case 10:
      return "清理地牢";
    case 11:
      return "征服城堡";
    case 12:
      return "施放法术";
    case 13:
      return "用剑攻击";
    case 14:
      return "用弓攻击";
    case 15:
      return "召唤宠物";
    case 16:
      return "等级提升";
    case 17:
      return "探索地牢";
    case 18:
      return "找到道具";
    case 19:
      return "找到好点的道具";
    case 20:
      return "找到好的道具";
    case 21:
      return "找到很好的道具";
    case 22:
      return "找到极好的道具";
    case 23:
      return "使用小型队伍进行游戏";
    case 24:
      return "使用多余的队伍进行游戏";
    case 25:
      return "用不同的职业进行游戏";
    case 26:
      return "不进行重生";
    case 27:
      return "单人队伍";
    case 28:
      return "使用召唤者";
  }
}
export function resetAchievements() {
  var a = game.state.achievements,
    b;
  for (b = 0; b < a.jj.length; b++) {
    var c = a.jj[b];
    c.Of = false;
    c.We = false;
  }
  a.ik.length = 0;
  a.Ze.length = 0;
}
export function initializeProgressionAchievements() {
  achievementDefinitions = [{
    id: "monsterKills100",
    name: "杀死100个怪物",
    requirementType: 1,
    requiredCount: 100,
    pointEventTypeId: 1
  }, {
    id: "monsterKills1000",
    name: "杀死1,000个怪物",
    requirementType: 1,
    requiredCount: 1E3,
    pointEventTypeId: 21
  }, {
    id: "monsterKills5K",
    name: "杀死5,000个怪物",
    requirementType: 1,
    requiredCount: 5E3,
    pointEventTypeId: 1
  }, {
    id: "monsterKills10K",
    name: "杀死10,000个怪物",
    requirementType: 1,
    requiredCount: 1E4,
    pointEventTypeId: 13
  }, {
    id: "monsterKills25K",
    name: "杀死25,000个怪物",
    requirementType: 1,
    requiredCount: 25E3,
    pointEventTypeId: 1
  }, {
    id: "monsterKills50K",
    name: "杀死50,000个怪物",
    requirementType: 1,
    requiredCount: 5E4,
    pointEventTypeId: 14
  }, {
    id: "monsterKills100K",
    name: "杀死100,000个怪物",
    requirementType: 1,
    requiredCount: 1E5,
    pointEventTypeId: 1
  }, {
    id: "monsterKills250K",
    name: "杀死250,000个怪物",
    requirementType: 1,
    requiredCount: 25E4,
    pointEventTypeId: 15
  }, {
    id: "monsterKills500K",
    name: "杀死500,000个怪物",
    requirementType: 1,
    requiredCount: 5E5,
    pointEventTypeId: 1
  }, {
    id: "monsterKills1M",
    name: "杀死1,000,000个怪物",
    requirementType: 1,
    requiredCount: 1E6,
    pointEventTypeId: 16
  }, {
    id: "monsterKills2M",
    name: "杀死2,000,000个怪物",
    requirementType: 1,
    requiredCount: 2E6,
    pointEventTypeId: 2
  }, {
    id: "scrollKills100",
    name: "100个怪物被卷轴杀死",
    requirementType: 2,
    requiredCount: 100,
    pointEventTypeId: 2
  }, {
    id: "scrollKills500",
    name: "500个怪物被卷轴杀死",
    requirementType: 2,
    requiredCount: 500,
    pointEventTypeId: 22
  }, {
    id: "scrollKills1000",
    name: "1,000个怪物被卷轴杀死",
    requirementType: 2,
    requiredCount: 1E3,
    pointEventTypeId: POINT_EVENT_ENCOUNTER
  }, {
    id: "scrollKills2K",
    name: "2,000个怪物被卷轴杀死",
    requirementType: 2,
    requiredCount: 2E3,
    pointEventTypeId: 9
  }, {
    id: "scrollKills3K",
    name: "3,000个怪物被卷轴杀死",
    requirementType: 2,
    requiredCount: 3E3,
    pointEventTypeId: 12
  }, {
    id: "scrollKills5K",
    name: "5,000个怪物被卷轴杀死",
    requirementType: 2,
    requiredCount: 5E3,
    pointEventTypeId: 1
  }, {
    id: "scrollKills7K",
    name: "7,000个怪物被卷轴杀死",
    requirementType: 2,
    requiredCount: 7E3,
    pointEventTypeId: 7
  }, {
    id: "scrollKills10K",
    name: "10,000个怪物被卷轴杀死",
    requirementType: 2,
    requiredCount: 1E4,
    pointEventTypeId: 2
  }, {
    id: "scrollKills15K",
    name: "15,000个怪物被卷轴杀死",
    requirementType: 2,
    requiredCount: 15E3,
    pointEventTypeId: 19
  }, {
    id: "scrollKills20K",
    name: "20,000个怪物被卷轴杀死",
    requirementType: 2,
    requiredCount: 2E4,
    pointEventTypeId: 21
  }, {
    id: "scrollUses100",
    name: "100个卷轴已使用",
    requirementType: 3,
    requiredCount: 100,
    pointEventTypeId: 10
  }, {
    id: "scrollUses300",
    name: "300个卷轴已使用",
    requirementType: 3,
    requiredCount: 300,
    pointEventTypeId: 18
  }, {
    id: "scrollUses500",
    name: "500个卷轴已使用",
    requirementType: 3,
    requiredCount: 500,
    pointEventTypeId: POINT_EVENT_DUNGEON_CLEARED
  }, {
    id: "scrollUses750",
    name: "750个卷轴已使用",
    requirementType: 3,
    requiredCount: 750,
    pointEventTypeId: 21
  }, {
    id: "scrollUses1000",
    name: "1,000个卷轴已使用",
    requirementType: 3,
    requiredCount: 1E3,
    pointEventTypeId: 13
  }, {
    id: "scrollUses2K",
    name: "2,000个卷轴已使用",
    requirementType: 3,
    requiredCount: 2E3,
    pointEventTypeId: 14
  }, {
    id: "scrollUses3K",
    name: "3,000个卷轴已使用",
    requirementType: 3,
    requiredCount: 3E3,
    pointEventTypeId: 15
  }, {
    id: "scrollUses4K",
    name: "4,000个卷轴已使用",
    requirementType: 3,
    requiredCount: 4E3,
    pointEventTypeId: 16
  }, {
    id: "scrollUses5K",
    name: "5,000个卷轴已使用",
    requirementType: 3,
    requiredCount: 5E3,
    pointEventTypeId: 17
  }, {
    id: "scrollUses7500",
    name: "7,500个卷轴已使用",
    requirementType: 3,
    requiredCount: 7500,
    pointEventTypeId: 18
  }, {
    id: "scrollUses15K",
    name: "15,000个卷轴已使用",
    requirementType: 3,
    requiredCount: 15E3,
    pointEventTypeId: 21
  }, {
    id: "scrollUses30K",
    name: "30,000个卷轴已使用",
    requirementType: 3,
    requiredCount: 3E4,
    pointEventTypeId: 6
  }, {
    id: "scrollUses45K",
    name: "45,000个卷轴已使用",
    requirementType: 3,
    requiredCount: 45E3,
    pointEventTypeId: 7
  }, {
    id: "scrollUses60K",
    name: "60,000个卷轴已使用",
    requirementType: 3,
    requiredCount: 6E4,
    pointEventTypeId: 8
  }, {
    id: "potionUses100",
    name: "100药剂已使用",
    requirementType: 4,
    requiredCount: 100,
    pointEventTypeId: 8
  }, {
    id: "potionUses200",
    name: "200药剂已使用",
    requirementType: 4,
    requiredCount: 200,
    pointEventTypeId: 7
  }, {
    id: "potionUses300",
    name: "300药剂已使用",
    requirementType: 4,
    requiredCount: 300,
    pointEventTypeId: 6
  }, {
    id: "potionUses400",
    name: "400药剂已使用",
    requirementType: 4,
    requiredCount: 400,
    pointEventTypeId: 11
  }, {
    id: "potionUses500",
    name: "500药剂已使用",
    requirementType: 4,
    requiredCount: 500,
    pointEventTypeId: 10
  }, {
    id: "potionUses750",
    name: "750药剂已使用",
    requirementType: 4,
    requiredCount: 750,
    pointEventTypeId: 2
  }, {
    id: "potionUses1000",
    name: "1000药剂已使用",
    requirementType: 4,
    requiredCount: 1E3,
    pointEventTypeId: 17
  }, {
    id: "potionUses1250",
    name: "1250药剂已使用",
    requirementType: 4,
    requiredCount: 1250,
    pointEventTypeId: 11
  }, {
    id: "potionUses2K",
    name: "2000药剂已使用",
    requirementType: 4,
    requiredCount: 2E3,
    pointEventTypeId: 10
  }, {
    id: "potionUses2500",
    name: "2500药剂已使用",
    requirementType: 4,
    requiredCount: 2500,
    pointEventTypeId: 21
  }, {
    id: "potionUses3K",
    name: "3000药剂已使用",
    requirementType: 4,
    requiredCount: 3E3,
    pointEventTypeId: 17
  }, {
    id: "treasureChests10",
    name: "10个财宝箱已搜索",
    requirementType: 5,
    requiredCount: 10,
    pointEventTypeId: 6
  }, {
    id: "treasureChests25",
    name: "25个财宝箱已搜索",
    requirementType: 5,
    requiredCount: 25,
    pointEventTypeId: 17
  }, {
    id: "treasureChests50",
    name: "50个财宝箱已搜索",
    requirementType: 5,
    requiredCount: 50,
    pointEventTypeId: 9
  }, {
    id: "treasureChests75",
    name: "75个财宝箱已搜索",
    requirementType: 5,
    requiredCount: 75,
    pointEventTypeId: 11
  }, {
    id: "treasureChests100",
    name: "100个财宝箱已搜索",
    requirementType: 5,
    requiredCount: 100,
    pointEventTypeId: 10
  }, {
    id: "treasureChests125",
    name: "125个财宝箱已搜索",
    requirementType: 5,
    requiredCount: 125,
    pointEventTypeId: 18
  }, {
    id: "treasureChests1K",
    name: "1000个财宝箱已搜索",
    requirementType: 5,
    requiredCount: 1E3,
    pointEventTypeId: 2
  }, {
    id: "treasureChests2500",
    name: "2500个财宝箱已搜索",
    requirementType: 5,
    requiredCount: 2500,
    pointEventTypeId: 9
  }, {
    id: "treasureChests5K",
    name: "5,000个财宝箱已搜索",
    requirementType: 5,
    requiredCount: 5E3,
    pointEventTypeId: 12
  }, {
    id: "treasureChests10K",
    name: "10,000个财宝箱已搜索",
    requirementType: 5,
    requiredCount: 1E4,
    pointEventTypeId: 11
  }, {
    id: "treasureChests20K",
    name: "20,000个财宝箱已搜索",
    requirementType: 5,
    requiredCount: 2E4,
    pointEventTypeId: POINT_EVENT_DUNGEON_CLEARED
  }, {
    id: "weaponRacks10",
    name: "10个武器架已搜索",
    requirementType: 6,
    requiredCount: 10,
    pointEventTypeId: 7
  }, {
    id: "weaponRacks25",
    name: "25个武器架已搜索",
    requirementType: 6,
    requiredCount: 25,
    pointEventTypeId: 13
  }, {
    id: "weaponRacks50",
    name: "50个武器架已搜索",
    requirementType: 6,
    requiredCount: 50,
    pointEventTypeId: 14
  }, {
    id: "weaponRacks75",
    name: "75个武器架已搜索",
    requirementType: 6,
    requiredCount: 75,
    pointEventTypeId: 15
  }, {
    id: "weaponRacks100",
    name: "100个武器架已搜索",
    requirementType: 6,
    requiredCount: 100,
    pointEventTypeId: 16
  }, {
    id: "weaponRacks125",
    name: "125个武器架已搜索",
    requirementType: 6,
    requiredCount: 125,
    pointEventTypeId: 17
  }, {
    id: "weaponRacks1K",
    name: "1,000个武器架已搜索",
    requirementType: 6,
    requiredCount: 1E3,
    pointEventTypeId: 13
  }, {
    id: "weaponRacks2500",
    name: "2,500个武器架已搜索",
    requirementType: 6,
    requiredCount: 2500,
    pointEventTypeId: 14
  }, {
    id: "weaponRacks5K",
    name: "5,000个武器架已搜索",
    requirementType: 6,
    requiredCount: 5E3,
    pointEventTypeId: 15
  }, {
    id: "weaponRacks10K",
    name: "10,000个武器架已搜索",
    requirementType: 6,
    requiredCount: 1E4,
    pointEventTypeId: 16
  }, {
    id: "weaponRacks20K",
    name: "20,000个武器架已搜索",
    requirementType: 6,
    requiredCount: 2E4,
    pointEventTypeId: 8
  }, {
    id: "bookcases10",
    name: "10个书架已搜索",
    requirementType: 7,
    requiredCount: 10,
    pointEventTypeId: 8
  }, {
    id: "bookcases25",
    name: "25个书架已搜索",
    requirementType: 7,
    requiredCount: 25,
    pointEventTypeId: 7
  }, {
    id: "bookcases50",
    name: "50个书架已搜索",
    requirementType: 7,
    requiredCount: 50,
    pointEventTypeId: 6
  }, {
    id: "bookcases75",
    name: "75个书架已搜索",
    requirementType: 7,
    requiredCount: 75,
    pointEventTypeId: 8
  }, {
    id: "bookcases100",
    name: "100个书架已搜索",
    requirementType: 7,
    requiredCount: 100,
    pointEventTypeId: 7
  }, {
    id: "bookcases125",
    name: "125个书架已搜索",
    requirementType: 7,
    requiredCount: 125,
    pointEventTypeId: 6
  }, {
    id: "bookcases1K",
    name: "1,000个书架已搜索",
    requirementType: 7,
    requiredCount: 1E3,
    pointEventTypeId: 11
  }, {
    id: "bookcases2500",
    name: "2,500个书架已搜索",
    requirementType: 7,
    requiredCount: 2500,
    pointEventTypeId: POINT_EVENT_ENCOUNTER
  }, {
    id: "bookcases5K",
    name: "5,000个书架已搜索",
    requirementType: 7,
    requiredCount: 5E3,
    pointEventTypeId: 18
  }, {
    id: "bookcases9K",
    name: "9,000个书架已搜索",
    requirementType: 7,
    requiredCount: 9E3,
    pointEventTypeId: 22
  }, {
    id: "itemsSold100",
    name: "100个道具已卖出",
    requirementType: 8,
    requiredCount: 100,
    pointEventTypeId: 17
  }, {
    id: "itemsSold500",
    name: "500个道具已卖出",
    requirementType: 8,
    requiredCount: 500,
    pointEventTypeId: POINT_EVENT_ENCOUNTER
  }, {
    id: "itemsSold1000",
    name: "1,000个道具已卖出",
    requirementType: 8,
    requiredCount: 1E3,
    pointEventTypeId: 17
  }, {
    id: "itemsSold2K",
    name: "2,000个道具已卖出",
    requirementType: 8,
    requiredCount: 2E3,
    pointEventTypeId: 9
  }, {
    id: "itemsSold3K",
    name: "3,000个道具已卖出",
    requirementType: 8,
    requiredCount: 3E3,
    pointEventTypeId: 10
  }, {
    id: "itemsSold5K",
    name: "5,000个道具已卖出",
    requirementType: 8,
    requiredCount: 5E3,
    pointEventTypeId: 11
  }, {
    id: "itemsSold10K",
    name: "10,000个道具已卖出",
    requirementType: 8,
    requiredCount: 1E4,
    pointEventTypeId: 12
  }, {
    id: "itemsSold15K",
    name: "15,000个道具已卖出",
    requirementType: 8,
    requiredCount: 15E3,
    pointEventTypeId: POINT_EVENT_LEVEL_CLEARED
  }, {
    id: "itemsSold20K",
    name: "20,000个道具已卖出",
    requirementType: 8,
    requiredCount: 2E4,
    pointEventTypeId: 1
  }, {
    id: "itemsSold40K",
    name: "40,000个道具已卖出",
    requirementType: 8,
    requiredCount: 4E4,
    pointEventTypeId: 16
  }, {
    id: "itemsSold60K",
    name: "60,000个道具已卖出",
    requirementType: 8,
    requiredCount: 6E4,
    pointEventTypeId: 8
  }, {
    id: "itemsSold80K",
    name: "80,000个道具已卖出",
    requirementType: 8,
    requiredCount: 8E4,
    pointEventTypeId: 21
  }, {
    id: "itemsSold100K",
    name: "100,000个道具已卖出",
    requirementType: 8,
    requiredCount: 1E5,
    pointEventTypeId: 17
  }, {
    id: "farmsPurchased5",
    name: "5个农场已购买",
    requirementType: 9,
    requiredCount: 5,
    pointEventTypeId: 2
  }, {
    id: "farmsPurchased15",
    name: "15个农场已购买",
    requirementType: 9,
    requiredCount: 15,
    pointEventTypeId: 9
  }, {
    id: "farmsPurchased25",
    name: "25个农场已购买",
    requirementType: 9,
    requiredCount: 25,
    pointEventTypeId: 12
  }, {
    id: "farmsPurchased50",
    name: "50个农场已购买",
    requirementType: 9,
    requiredCount: 50,
    pointEventTypeId: 10
  }, {
    id: "farmsPurchased75",
    name: "75个农场已购买",
    requirementType: 9,
    requiredCount: 75,
    pointEventTypeId: 11
  }, {
    id: "farmsPurchased100",
    name: "100个农场已购买",
    requirementType: 9,
    requiredCount: 100,
    pointEventTypeId: 13
  }, {
    id: "farmsPurchased150",
    name: "150个农场已购买",
    requirementType: 9,
    requiredCount: 150,
    pointEventTypeId: 14
  }, {
    id: "farmsPurchased200",
    name: "200个农场已购买",
    requirementType: 9,
    requiredCount: 200,
    pointEventTypeId: 15
  }, {
    id: "farmsPurchased250",
    name: "250个农场已购买",
    requirementType: 9,
    requiredCount: 250,
    pointEventTypeId: 16
  }, {
    id: "farmsPurchased300",
    name: "300个农场已购买",
    requirementType: 9,
    requiredCount: 300,
    pointEventTypeId: POINT_EVENT_DUNGEON_CLEARED
  }, {
    id: "farmsPurchased500",
    name: "500个农场已购买",
    requirementType: 9,
    requiredCount: 500,
    pointEventTypeId: 2
  }, {
    id: "farmsPurchased600",
    name: "600个农场已购买",
    requirementType: 9,
    requiredCount: 600,
    pointEventTypeId: 22
  }, {
    id: "farmsPurchased700",
    name: "700个农场已购买",
    requirementType: 9,
    requiredCount: 700,
    pointEventTypeId: 21
  }, {
    id: "dungeonsCleared10",
    name: "10个地牢已清理",
    requirementType: 10,
    requiredCount: 10,
    pointEventTypeId: POINT_EVENT_DUNGEON_CLEARED
  }, {
    id: "dungeonsCleared25",
    name: "25个地牢已清理",
    requirementType: 10,
    requiredCount: 25,
    pointEventTypeId: 19
  }, {
    id: "dungeonsCleared50",
    name: "50个地牢已清理",
    requirementType: 10,
    requiredCount: 50,
    pointEventTypeId: POINT_EVENT_LEVEL_CLEARED
  }, {
    id: "dungeonsCleared100",
    name: "100个地牢已清理",
    requirementType: 10,
    requiredCount: 100,
    pointEventTypeId: 17
  }, {
    id: "dungeonsCleared200",
    name: "200个地牢已清理",
    requirementType: 10,
    requiredCount: 200,
    pointEventTypeId: 8
  }, {
    id: "dungeonsCleared300",
    name: "300个地牢已清理",
    requirementType: 10,
    requiredCount: 300,
    pointEventTypeId: 7
  }, {
    id: "dungeonsCleared400",
    name: "400个地牢已清理",
    requirementType: 10,
    requiredCount: 400,
    pointEventTypeId: 6
  }, {
    id: "dungeonsCleared500",
    name: "500个地牢已清理",
    requirementType: 10,
    requiredCount: 500,
    pointEventTypeId: POINT_EVENT_ENCOUNTER
  }, {
    id: "dungeonsCleared750",
    name: "750个地牢已清理",
    requirementType: 10,
    requiredCount: 750,
    pointEventTypeId: POINT_EVENT_DUNGEON_CLEARED
  }, {
    id: "dungeonsCleared1K",
    name: "1,000个地牢已清理",
    requirementType: 10,
    requiredCount: 1E3,
    pointEventTypeId: 21
  }, {
    id: "dungeonsCleared1500",
    name: "1,500个地牢已清理",
    requirementType: 10,
    requiredCount: 1500,
    pointEventTypeId: POINT_EVENT_LEVEL_CLEARED
  }, {
    id: "dungeonsCleared2K",
    name: "2,000个地牢已清理",
    requirementType: 10,
    requiredCount: 2E3,
    pointEventTypeId: 17
  }, {
    id: "dungeonsCleared3K",
    name: "3,000个地牢已清理",
    requirementType: 10,
    requiredCount: 3E3,
    pointEventTypeId: 21
  }, {
    id: "dungeonsCleared4K",
    name: "4,000个地牢已清理",
    requirementType: 10,
    requiredCount: 4E3,
    pointEventTypeId: 22
  }, {
    id: "castlesConquered5",
    name: "5个城堡已征服",
    requirementType: 11,
    requiredCount: 5,
    pointEventTypeId: 19
  }, {
    id: "castlesConquered30",
    name: "30个城堡已征服",
    requirementType: 11,
    requiredCount: 30,
    pointEventTypeId: POINT_EVENT_DUNGEON_CLEARED
  }, {
    id: "castlesConquered60",
    name: "60个城堡已征服",
    requirementType: 11,
    requiredCount: 60,
    pointEventTypeId: 2
  }, {
    id: "castlesConquered90",
    name: "90个城堡已征服",
    requirementType: 11,
    requiredCount: 90,
    pointEventTypeId: 9
  }, {
    id: "castlesConquered120",
    name: "120个城堡已征服",
    requirementType: 11,
    requiredCount: 120,
    pointEventTypeId: 11
  }, {
    id: "castlesConquered150",
    name: "150个城堡已征服",
    requirementType: 11,
    requiredCount: 150,
    pointEventTypeId: 10
  }, {
    id: "castlesConquered180",
    name: "180个城堡已征服",
    requirementType: 11,
    requiredCount: 180,
    pointEventTypeId: 12
  }, {
    id: "castlesConquered210",
    name: "210个城堡已征服",
    requirementType: 11,
    requiredCount: 210,
    pointEventTypeId: 2
  }, {
    id: "castlesConquered240",
    name: "240个城堡已征服",
    requirementType: 11,
    requiredCount: 240,
    pointEventTypeId: 8
  }, {
    id: "castlesConquered270",
    name: "270个城堡已征服",
    requirementType: 11,
    requiredCount: 270,
    pointEventTypeId: POINT_EVENT_ENCOUNTER
  }, {
    id: "castlesConquered300",
    name: "300个城堡已征服",
    requirementType: 11,
    requiredCount: 300,
    pointEventTypeId: 19
  }, {
    id: "spellsCast1000",
    name: "1,000次法术施放",
    requirementType: 12,
    requiredCount: 1E3,
    pointEventTypeId: POINT_EVENT_LEVEL_CLEARED
  }, {
    id: "spellsCast5K",
    name: "5,000次法术施放",
    requirementType: 12,
    requiredCount: 5E3,
    pointEventTypeId: POINT_EVENT_DUNGEON_CLEARED
  }, {
    id: "spellsCast25K",
    name: "25,000次法术施放",
    requirementType: 12,
    requiredCount: 25E3,
    pointEventTypeId: 19
  }, {
    id: "spellsCast50K",
    name: "50,000次法术施放",
    requirementType: 12,
    requiredCount: 5E4,
    pointEventTypeId: 16
  }, {
    id: "spellsCast100K",
    name: "100,000次法术施放",
    requirementType: 12,
    requiredCount: 1E5,
    pointEventTypeId: 15
  }, {
    id: "spellsCast150K",
    name: "150,000次法术施放",
    requirementType: 12,
    requiredCount: 15E4,
    pointEventTypeId: 14
  }, {
    id: "spellsCast200K",
    name: "200,000次法术施放",
    requirementType: 12,
    requiredCount: 2E5,
    pointEventTypeId: 13
  }, {
    id: "spellsCast300K",
    name: "300,000次法术施放",
    requirementType: 12,
    requiredCount: 3E5,
    pointEventTypeId: 9
  }, {
    id: "spellsCast500K",
    name: "500,000次法术施放",
    requirementType: 12,
    requiredCount: 5E5,
    pointEventTypeId: 12
  }, {
    id: "spellsCast700K",
    name: "700,000次法术施放",
    requirementType: 12,
    requiredCount: 7E5,
    pointEventTypeId: 11
  }, {
    id: "spellsCast900K",
    name: "900,000次法术施放",
    requirementType: 12,
    requiredCount: 9E5,
    pointEventTypeId: 10
  }, {
    id: "spellsCast1.1M",
    name: "1,100,000次法术施放",
    requirementType: 12,
    requiredCount: 11E5,
    pointEventTypeId: 21
  }, {
    id: "meleeAttacks1000",
    name: "1,000次近战攻击",
    requirementType: 13,
    requiredCount: 1E3,
    pointEventTypeId: 21
  }, {
    id: "meleeAttacks5K",
    name: "5,000次近战攻击",
    requirementType: 13,
    requiredCount: 5E3,
    pointEventTypeId: 9
  }, {
    id: "meleeAttacks25K",
    name: "25,000次近战攻击",
    requirementType: 13,
    requiredCount: 25E3,
    pointEventTypeId: 12
  }, {
    id: "meleeAttacks50K",
    name: "50,000次近战攻击",
    requirementType: 13,
    requiredCount: 5E4,
    pointEventTypeId: 11
  }, {
    id: "meleeAttacks100K",
    name: "100,000次近战攻击",
    requirementType: 13,
    requiredCount: 1E5,
    pointEventTypeId: 10
  }, {
    id: "meleeAttacks150K",
    name: "150,000次近战攻击",
    requirementType: 13,
    requiredCount: 15E4,
    pointEventTypeId: POINT_EVENT_LEVEL_CLEARED
  }, {
    id: "meleeAttacks200K",
    name: "200,000次近战攻击",
    requirementType: 13,
    requiredCount: 2E5,
    pointEventTypeId: 2
  }, {
    id: "meleeAttacks400K",
    name: "400,000次近战攻击",
    requirementType: 13,
    requiredCount: 4E5,
    pointEventTypeId: 22
  }, {
    id: "meleeAttacks700K",
    name: "700,000次近战攻击",
    requirementType: 13,
    requiredCount: 7E5,
    pointEventTypeId: 17
  }, {
    id: "meleeAttacks1M",
    name: "1,000,000次近战攻击",
    requirementType: 13,
    requiredCount: 1E6,
    pointEventTypeId: 19
  }, {
    id: "meleeAttacks1.5M",
    name: "1,500,000次近战攻击",
    requirementType: 13,
    requiredCount: 15E5,
    pointEventTypeId: 9
  }, {
    id: "meleeAttacks2M",
    name: "2,000,000次近战攻击",
    requirementType: 13,
    requiredCount: 2E6,
    pointEventTypeId: 11
  }, {
    id: "meleeAttacks3M",
    name: "3,000,000次近战攻击",
    requirementType: 13,
    requiredCount: 3E6,
    pointEventTypeId: 10
  }, {
    id: "rangedAttacks1000",
    name: "1,000次远程攻击",
    requirementType: 14,
    requiredCount: 1E3,
    pointEventTypeId: POINT_EVENT_DUNGEON_CLEARED
  }, {
    id: "rangedAttacks5K",
    name: "5,000次远程攻击",
    requirementType: 14,
    requiredCount: 5E3,
    pointEventTypeId: 9
  }, {
    id: "rangedAttacks25K",
    name: "25,000次远程攻击",
    requirementType: 14,
    requiredCount: 25E3,
    pointEventTypeId: 11
  }, {
    id: "rangedAttacks50K",
    name: "50,000次远程攻击",
    requirementType: 14,
    requiredCount: 5E4,
    pointEventTypeId: 10
  }, {
    id: "rangedAttacks100K",
    name: "100,000次远程攻击",
    requirementType: 14,
    requiredCount: 1E5,
    pointEventTypeId: 12
  }, {
    id: "rangedAttacks150K",
    name: "150,000次远程攻击",
    requirementType: 14,
    requiredCount: 15E4,
    pointEventTypeId: POINT_EVENT_LEVEL_CLEARED
  }, {
    id: "rangedAttacks200K",
    name: "200,000次远程攻击",
    requirementType: 14,
    requiredCount: 2E5,
    pointEventTypeId: 22
  }, {
    id: "rangedAttacks300K",
    name: "300,000次远程攻击",
    requirementType: 14,
    requiredCount: 3E5,
    pointEventTypeId: 17
  }, {
    id: "rangedAttacks400K",
    name: "400,000次远程攻击",
    requirementType: 14,
    requiredCount: 4E5,
    pointEventTypeId: 19
  }, {
    id: "rangedAttacks500K",
    name: "500,000次远程攻击",
    requirementType: 14,
    requiredCount: 5E5,
    pointEventTypeId: 10
  }, {
    id: "rangedAttacks700K",
    name: "700,000次远程攻击",
    requirementType: 14,
    requiredCount: 7E5,
    pointEventTypeId: 11
  }, {
    id: "rangedAttacks900K",
    name: "900,000次远程攻击",
    requirementType: 14,
    requiredCount: 9E5,
    pointEventTypeId: 9
  }, {
    id: "rangedAttacks1.2M",
    name: "1,200,000次远程攻击",
    requirementType: 14,
    requiredCount: 12E5,
    pointEventTypeId: 21
  }, {
    id: "minionsSummoned50",
    name: "50次宠物召唤",
    requirementType: 15,
    requiredCount: 50,
    pointEventTypeId: POINT_EVENT_DUNGEON_CLEARED
  }, {
    id: "minionsSummoned100",
    name: "100次宠物召唤",
    requirementType: 15,
    requiredCount: 100,
    pointEventTypeId: POINT_EVENT_LEVEL_CLEARED
  }, {
    id: "minionsSummoned250",
    name: "250次宠物召唤",
    requirementType: 15,
    requiredCount: 250,
    pointEventTypeId: 19
  }, {
    id: "minionsSummoned500",
    name: "500次宠物召唤",
    requirementType: 15,
    requiredCount: 500,
    pointEventTypeId: 7
  }, {
    id: "minionsSummoned750",
    name: "750次宠物召唤",
    requirementType: 15,
    requiredCount: 750,
    pointEventTypeId: 8
  }, {
    id: "minionsSummoned1000",
    name: "1,000次宠物召唤",
    requirementType: 15,
    requiredCount: 1E3,
    pointEventTypeId: 6
  }, {
    id: "minionsSummoned1500",
    name: "1,500次宠物召唤",
    requirementType: 15,
    requiredCount: 1500,
    pointEventTypeId: 22
  }, {
    id: "minionsSummoned2K",
    name: "2,000次宠物召唤",
    requirementType: 15,
    requiredCount: 2E3,
    pointEventTypeId: 9
  }, {
    id: "minionsSummoned3K",
    name: "3,000次宠物召唤",
    requirementType: 15,
    requiredCount: 3E3,
    pointEventTypeId: 11
  }, {
    id: "minionsSummoned5K",
    name: "5,000次宠物召唤",
    requirementType: 15,
    requiredCount: 5E3,
    pointEventTypeId: 10
  }, {
    id: "minionsSummoned30K",
    name: "30,000次宠物召唤",
    requirementType: 15,
    requiredCount: 3E4,
    pointEventTypeId: 17
  }, {
    id: "minionsSummoned50K",
    name: "50,000次宠物召唤",
    requirementType: 15,
    requiredCount: 5E4,
    pointEventTypeId: 14
  }, {
    id: "minionsSummoned75K",
    name: "75,000次宠物召唤",
    requirementType: 15,
    requiredCount: 75E3,
    pointEventTypeId: 15
  }, {
    id: "minionsSummoned100K",
    name: "100,000次宠物召唤",
    requirementType: 15,
    requiredCount: 1E5,
    pointEventTypeId: 13
  }, {
    id: "minionsSummoned125K",
    name: "125,000次宠物召唤",
    requirementType: 15,
    requiredCount: 125E3,
    pointEventTypeId: 16
  }, {
    id: "minionsSummoned150K",
    name: "150,000次宠物召唤",
    requirementType: 15,
    requiredCount: 15E4,
    pointEventTypeId: 21
  }, {
    id: "minionsSummoned200K",
    name: "200,000次宠物召唤",
    requirementType: 15,
    requiredCount: 2E5,
    pointEventTypeId: POINT_EVENT_ENCOUNTER
  }, {
    id: "minionKills100",
    name: "100个怪被宠物杀死",
    requirementType: 28,
    requiredCount: 100,
    pointEventTypeId: 2
  }, {
    id: "minionKills1K",
    name: "1,000个怪被宠物杀死",
    requirementType: 28,
    requiredCount: 1E3,
    pointEventTypeId: 19
  }, {
    id: "minionKills5K",
    name: "5,000个怪被宠物杀死",
    requirementType: 28,
    requiredCount: 5E3,
    pointEventTypeId: 17
  }, {
    id: "minionKills10K",
    name: "10,000个怪被宠物杀死",
    requirementType: 28,
    requiredCount: 1E4,
    pointEventTypeId: 18
  }, {
    id: "minionKills25K",
    name: "25,000个怪被宠物杀死",
    requirementType: 28,
    requiredCount: 25E3,
    pointEventTypeId: 21
  }, {
    id: "minionKills50K",
    name: "50,000个怪被宠物杀死",
    requirementType: 28,
    requiredCount: 5E4,
    pointEventTypeId: 22
  }, {
    id: "minionKills100K",
    name: "100,000个怪被宠物杀死",
    requirementType: 28,
    requiredCount: 1E5,
    pointEventTypeId: POINT_EVENT_ENCOUNTER
  }, {
    id: "minionKills250K",
    name: "250,000个怪被宠物杀死",
    requirementType: 28,
    requiredCount: 25E4,
    pointEventTypeId: 11
  }, {
    id: "minionKills500K",
    name: "500,000个怪被宠物杀死",
    requirementType: 28,
    requiredCount: 5E5,
    pointEventTypeId: 18
  }, {
    id: "minionKills750K",
    name: "750,000个怪被宠物杀死",
    requirementType: 28,
    requiredCount: 75E4,
    pointEventTypeId: 8
  }, {
    id: "minionKills1M",
    name: "1,000,000个怪被宠物杀死",
    requirementType: 28,
    requiredCount: 1E6,
    pointEventTypeId: 22
  }, {
    id: "characterLevel15",
    name: "角色等级达到15",
    requirementType: 16,
    requiredCount: 15,
    pointEventTypeId: 13
  }, {
    id: "characterLevel30",
    name: "角色等级达到30",
    requirementType: 16,
    requiredCount: 30,
    pointEventTypeId: 14
  }, {
    id: "characterLevel45",
    name: "角色等级达到45",
    requirementType: 16,
    requiredCount: 45,
    pointEventTypeId: 15
  }, {
    id: "characterLevel60",
    name: "角色等级达到60",
    requirementType: 16,
    requiredCount: 60,
    pointEventTypeId: 16
  }, {
    id: "characterLevel75",
    name: "角色等级达到75",
    requirementType: 16,
    requiredCount: 75,
    pointEventTypeId: 17
  }, {
    id: "characterLevel90",
    name: "角色等级达到90",
    requirementType: 16,
    requiredCount: 90,
    pointEventTypeId: 12
  }, {
    id: "characterLevel105",
    name: "角色等级达到105",
    requirementType: 16,
    requiredCount: 105,
    pointEventTypeId: 9
  }, {
    id: "characterLevel120",
    name: "角色等级达到120",
    requirementType: 16,
    requiredCount: 120,
    pointEventTypeId: 10
  }, {
    id: "characterLevel135",
    name: "角色等级达到135",
    requirementType: 16,
    requiredCount: 135,
    pointEventTypeId: 11
  }, {
    id: "doorsOpened500",
    name: "500扇门被打开",
    requirementType: 17,
    requiredCount: 500,
    pointEventTypeId: POINT_EVENT_ENCOUNTER
  }, {
    id: "doorsOpened1K",
    name: "1,000扇门被打开",
    requirementType: 17,
    requiredCount: 1E3,
    pointEventTypeId: 2
  }, {
    id: "doorsOpened2K",
    name: "2,000扇门被打开",
    requirementType: 17,
    requiredCount: 2E3,
    pointEventTypeId: 17
  }, {
    id: "doorsOpened3K",
    name: "3,000扇门被打开",
    requirementType: 17,
    requiredCount: 3E3,
    pointEventTypeId: 1
  }, {
    id: "doorsOpened4K",
    name: "4,000扇门被打开",
    requirementType: 17,
    requiredCount: 4E3,
    pointEventTypeId: 8
  }, {
    id: "doorsOpened5K",
    name: "5,000扇门被打开",
    requirementType: 17,
    requiredCount: 5E3,
    pointEventTypeId: 7
  }, {
    id: "doorsOpened7500",
    name: "7,500扇门被打开",
    requirementType: 17,
    requiredCount: 7500,
    pointEventTypeId: 6
  }, {
    id: "doorsOpened10K",
    name: "10,000扇门被打开",
    requirementType: 17,
    requiredCount: 1E4,
    pointEventTypeId: 13
  }, {
    id: "doorsOpened15K",
    name: "15,000扇门被打开",
    requirementType: 17,
    requiredCount: 15E3,
    pointEventTypeId: 14
  }, {
    id: "doorsOpened20K",
    name: "20,000扇门被打开",
    requirementType: 17,
    requiredCount: 2E4,
    pointEventTypeId: 15
  }, {
    id: "doorsOpened30K",
    name: "30,000扇门被打开",
    requirementType: 17,
    requiredCount: 3E4,
    pointEventTypeId: 16
  }, {
    id: "doorsOpened40K",
    name: "40,000扇门被打开",
    requirementType: 17,
    requiredCount: 4E4,
    pointEventTypeId: 1
  }, {
    id: "doorsOpened50K",
    name: "50,000扇门被打开",
    requirementType: 17,
    requiredCount: 5E4,
    pointEventTypeId: 2
  }, {
    id: "doorsOpened75K",
    name: "75,000扇门被打开",
    requirementType: 17,
    requiredCount: 75E3,
    pointEventTypeId: 21
  }, {
    id: "doorsOpened100K",
    name: "100,000扇门被打开",
    requirementType: 17,
    requiredCount: 1E5,
    pointEventTypeId: 22
  }, {
    id: "doorsOpened125K",
    name: "125,000扇门被打开",
    requirementType: 17,
    requiredCount: 125E3,
    pointEventTypeId: 16
  }, {
    id: "doorsOpened150K",
    name: "150,000扇门被打开",
    requirementType: 17,
    requiredCount: 15E4,
    pointEventTypeId: 15
  }, {
    id: "doorsOpened175K",
    name: "175,000扇门被打开",
    requirementType: 17,
    requiredCount: 175E3,
    pointEventTypeId: 14
  }, {
    id: "itemsFound500",
    name: "500个道具被找到",
    requirementType: 18,
    requiredCount: 500,
    pointEventTypeId: 12
  }, {
    id: "itemsFound1000",
    name: "1,000个道具被找到",
    requirementType: 18,
    requiredCount: 1E3,
    pointEventTypeId: 9
  }, {
    id: "itemsFound5K",
    name: "5,000个道具被找到",
    requirementType: 18,
    requiredCount: 5E3,
    pointEventTypeId: 11
  }, {
    id: "itemsFound10K",
    name: "10,000个道具被找到",
    requirementType: 18,
    requiredCount: 1E4,
    pointEventTypeId: 10
  }, {
    id: "itemsFound25K",
    name: "25,000个道具被找到",
    requirementType: 18,
    requiredCount: 25E3,
    pointEventTypeId: POINT_EVENT_LEVEL_CLEARED
  }, {
    id: "itemsFound50K",
    name: "50,000个道具被找到",
    requirementType: 18,
    requiredCount: 5E4,
    pointEventTypeId: POINT_EVENT_DUNGEON_CLEARED
  }, {
    id: "itemsFound100K",
    name: "100,000个道具被找到",
    requirementType: 18,
    requiredCount: 1E5,
    pointEventTypeId: 19
  }, {
    id: "itemsFound200K",
    name: "200,000个道具被找到",
    requirementType: 18,
    requiredCount: 2E5,
    pointEventTypeId: 1
  }, {
    id: "itemsFound300K",
    name: "300,000个道具被找到",
    requirementType: 18,
    requiredCount: 3E5,
    pointEventTypeId: 2
  }, {
    id: "itemsFound400K",
    name: "400,000个道具被找到",
    requirementType: 18,
    requiredCount: 4E5,
    pointEventTypeId: 9
  }, {
    id: "itemsFound500K",
    name: "500,000个道具被找到",
    requirementType: 18,
    requiredCount: 5E5,
    pointEventTypeId: 12
  }, {
    id: "itemsFound600K",
    name: "600,000个道具被找到",
    requirementType: 18,
    requiredCount: 6E5,
    pointEventTypeId: 11
  }, {
    id: "itemsFound700K",
    name: "700,000个道具被找到",
    requirementType: 18,
    requiredCount: 7E5,
    pointEventTypeId: 10
  }, {
    id: "itemsFound800K",
    name: "800,000个道具被找到",
    requirementType: 18,
    requiredCount: 8E5,
    pointEventTypeId: 12
  }, {
    id: "itemsFound1M",
    name: "1,000,000个道具被找到",
    requirementType: 18,
    requiredCount: 1E6,
    pointEventTypeId: POINT_EVENT_LEVEL_CLEARED
  }, {
    id: "itemsFound1.25M",
    name: "1,250,000个道具被找到",
    requirementType: 18,
    requiredCount: 125E4,
    pointEventTypeId: 22
  }, {
    id: "itemsFound1.5M",
    name: "1,500,000个道具被找到",
    requirementType: 18,
    requiredCount: 15E5,
    pointEventTypeId: 21
  }, {
    id: "uncommonItemsFound100",
    name: "100个罕见道具被找到",
    requirementType: 19,
    requiredCount: 100,
    pointEventTypeId: POINT_EVENT_LEVEL_CLEARED
  }, {
    id: "uncommonItemsFound250",
    name: "250个罕见道具被找到",
    requirementType: 19,
    requiredCount: 250,
    pointEventTypeId: POINT_EVENT_DUNGEON_CLEARED
  }, {
    id: "uncommonItemsFound500",
    name: "500个罕见道具被找到",
    requirementType: 19,
    requiredCount: 500,
    pointEventTypeId: POINT_EVENT_ENCOUNTER
  }, {
    id: "uncommonItemsFound1000",
    name: "1,000个罕见道具被找到",
    requirementType: 19,
    requiredCount: 1E3,
    pointEventTypeId: 13
  }, {
    id: "uncommonItemsFound2500",
    name: "2,500个罕见道具被找到",
    requirementType: 19,
    requiredCount: 2500,
    pointEventTypeId: 2
  }, {
    id: "uncommonItemsFound5000",
    name: "5,000个罕见道具被找到",
    requirementType: 19,
    requiredCount: 5E3,
    pointEventTypeId: 12
  }, {
    id: "uncommonItemsFound10K",
    name: "10,000个罕见道具被找到",
    requirementType: 19,
    requiredCount: 1E4,
    pointEventTypeId: 12
  }, {
    id: "uncommonItemsFound25K",
    name: "25,000个罕见道具被找到",
    requirementType: 19,
    requiredCount: 25E3,
    pointEventTypeId: 9
  }, {
    id: "uncommonItemsFound50K",
    name: "50,000个罕见道具被找到",
    requirementType: 19,
    requiredCount: 5E4,
    pointEventTypeId: 10
  }, {
    id: "uncommonItemsFound75K",
    name: "75,000个罕见道具被找到",
    requirementType: 19,
    requiredCount: 75E3,
    pointEventTypeId: 11
  }, {
    id: "uncommonItemsFound100K",
    name: "100,000个罕见道具被找到",
    requirementType: 19,
    requiredCount: 1E5,
    pointEventTypeId: 13
  }, {
    id: "uncommonItemsFound125K",
    name: "125,000个罕见道具被找到",
    requirementType: 19,
    requiredCount: 125E3,
    pointEventTypeId: 1
  }, {
    id: "uncommonItemsFound150K",
    name: "150,000个罕见道具被找到",
    requirementType: 19,
    requiredCount: 15E4,
    pointEventTypeId: 13
  }, {
    id: "uncommonItemsFound200K",
    name: "200,000个罕见道具被找到",
    requirementType: 19,
    requiredCount: 2E5,
    pointEventTypeId: POINT_EVENT_DUNGEON_CLEARED
  }, {
    id: "uncommonItemsFound250K",
    name: "250,000个罕见道具被找到",
    requirementType: 19,
    requiredCount: 25E4,
    pointEventTypeId: 19
  }, {
    id: "uncommonItemsFound300K",
    name: "300,000个罕见道具被找到",
    requirementType: 19,
    requiredCount: 3E5,
    pointEventTypeId: 22
  }, {
    id: "rareItemsFound50",
    name: "50个稀有道具被找到",
    requirementType: 20,
    requiredCount: 50,
    pointEventTypeId: 14
  }, {
    id: "rareItemsFound100",
    name: "100个稀有道具被找到",
    requirementType: 20,
    requiredCount: 100,
    pointEventTypeId: POINT_EVENT_LEVEL_CLEARED
  }, {
    id: "rareItemsFound250",
    name: "250个稀有道具被找到",
    requirementType: 20,
    requiredCount: 250,
    pointEventTypeId: 14
  }, {
    id: "rareItemsFound500",
    name: "500个稀有道具被找到",
    requirementType: 20,
    requiredCount: 500,
    pointEventTypeId: 1
  }, {
    id: "rareItemsFound1000",
    name: "1,000个稀有道具被找到",
    requirementType: 20,
    requiredCount: 1E3,
    pointEventTypeId: 14
  }, {
    id: "rareItemsFound2500",
    name: "2,500个稀有道具被找到",
    requirementType: 20,
    requiredCount: 2500,
    pointEventTypeId: 2
  }, {
    id: "rareItemsFound5K",
    name: "5,000个稀有道具被找到",
    requirementType: 20,
    requiredCount: 5E3,
    pointEventTypeId: 22
  }, {
    id: "rareItemsFound10K",
    name: "10,000个稀有道具被找到",
    requirementType: 20,
    requiredCount: 1E4,
    pointEventTypeId: 17
  }, {
    id: "rareItemsFound20K",
    name: "20,000个稀有道具被找到",
    requirementType: 20,
    requiredCount: 2E4,
    pointEventTypeId: 14
  }, {
    id: "rareItemsFound30K",
    name: "30,000个稀有道具被找到",
    requirementType: 20,
    requiredCount: 3E4,
    pointEventTypeId: 12
  }, {
    id: "rareItemsFound40K",
    name: "40,000个稀有道具被找到",
    requirementType: 20,
    requiredCount: 4E4,
    pointEventTypeId: 14
  }, {
    id: "rareItemsFound60K",
    name: "60,000个稀有道具被找到",
    requirementType: 20,
    requiredCount: 6E4,
    pointEventTypeId: 16
  }, {
    id: "rareItemsFound80K",
    name: "80,000个稀有道具被找到",
    requirementType: 20,
    requiredCount: 8E4,
    pointEventTypeId: 13
  }, {
    id: "rareItemsFound100K",
    name: "100,000个稀有道具被找到",
    requirementType: 20,
    requiredCount: 1E5,
    pointEventTypeId: 15
  }, {
    id: "historicItemsFound10",
    name: "10个历史道具被找到",
    requirementType: 21,
    requiredCount: 10,
    pointEventTypeId: 15
  }, {
    id: "historicItemsFound25",
    name: "25个历史道具被找到",
    requirementType: 21,
    requiredCount: 25,
    pointEventTypeId: 7
  }, {
    id: "historicItemsFound50",
    name: "50个历史道具被找到",
    requirementType: 21,
    requiredCount: 50,
    pointEventTypeId: 15
  }, {
    id: "historicItemsFound100",
    name: "100个历史道具被找到",
    requirementType: 21,
    requiredCount: 100,
    pointEventTypeId: 8
  }, {
    id: "historicItemsFound250",
    name: "250个历史道具被找到",
    requirementType: 21,
    requiredCount: 250,
    pointEventTypeId: 15
  }, {
    id: "historicItemsFound500",
    name: "500个历史道具被找到",
    requirementType: 21,
    requiredCount: 500,
    pointEventTypeId: 6
  }, {
    id: "historicItemsFound1000",
    name: "1,000个历史道具被找到",
    requirementType: 21,
    requiredCount: 1E3,
    pointEventTypeId: 15
  }, {
    id: "historicItemsFound1500",
    name: "1,500个历史道具被找到",
    requirementType: 21,
    requiredCount: 1500,
    pointEventTypeId: 2
  }, {
    id: "historicItemsFound2K",
    name: "2,000个历史道具被找到",
    requirementType: 21,
    requiredCount: 2E3,
    pointEventTypeId: 15
  }, {
    id: "historicItemsFound3K",
    name: "3,000个历史道具被找到",
    requirementType: 21,
    requiredCount: 3E3,
    pointEventTypeId: 18
  }, {
    id: "historicItemsFound4K",
    name: "4,000个历史道具被找到",
    requirementType: 21,
    requiredCount: 4E3,
    pointEventTypeId: 15
  }, {
    id: "historicItemsFound5K",
    name: "5,000个历史道具被找到",
    requirementType: 21,
    requiredCount: 5E3,
    pointEventTypeId: POINT_EVENT_LEVEL_CLEARED
  }, {
    id: "historicItemsFound6K",
    name: "6,000个历史道具被找到",
    requirementType: 21,
    requiredCount: 6E3,
    pointEventTypeId: 21
  }, {
    id: "historicItemsFound7K",
    name: "7,000个历史道具被找到",
    requirementType: 21,
    requiredCount: 7E3,
    pointEventTypeId: 8
  }, {
    id: "historicItemsFound8K",
    name: "8,000个历史道具被找到",
    requirementType: 21,
    requiredCount: 8E3,
    pointEventTypeId: 7
  }, {
    id: "ancientItemsFound3",
    name: "3个远古道具被找到",
    requirementType: 22,
    requiredCount: 3,
    pointEventTypeId: 16
  }, {
    id: "ancientItemsFound10",
    name: "10个远古道具被找到",
    requirementType: 22,
    requiredCount: 10,
    pointEventTypeId: 1
  }, {
    id: "ancientItemsFound25",
    name: "25个远古道具被找到",
    requirementType: 22,
    requiredCount: 25,
    pointEventTypeId: 16
  }, {
    id: "ancientItemsFound50",
    name: "50个远古道具被找到",
    requirementType: 22,
    requiredCount: 50,
    pointEventTypeId: 2
  }, {
    id: "ancientItemsFound75",
    name: "75个远古道具被找到",
    requirementType: 22,
    requiredCount: 75,
    pointEventTypeId: 16
  }, {
    id: "ancientItemsFound100",
    name: "100个远古道具被找到",
    requirementType: 22,
    requiredCount: 100,
    pointEventTypeId: 17
  }, {
    id: "ancientItemsFound150",
    name: "150个远古道具被找到",
    requirementType: 22,
    requiredCount: 150,
    pointEventTypeId: 16
  }, {
    id: "ancientItemsFound200",
    name: "200个远古道具被找到",
    requirementType: 22,
    requiredCount: 200,
    pointEventTypeId: POINT_EVENT_LEVEL_CLEARED
  }, {
    id: "ancientItemsFound300",
    name: "300个远古道具被找到",
    requirementType: 22,
    requiredCount: 300,
    pointEventTypeId: 16
  }, {
    id: "ancientItemsFound400",
    name: "400个远古道具被找到",
    requirementType: 22,
    requiredCount: 400,
    pointEventTypeId: 9
  }, {
    id: "ancientItemsFound500",
    name: "500个远古道具被找到",
    requirementType: 22,
    requiredCount: 500,
    pointEventTypeId: 12
  }, {
    id: "ancientItemsFound600",
    name: "600个远古道具被找到",
    requirementType: 22,
    requiredCount: 600,
    pointEventTypeId: 11
  }, {
    id: "ancientItemsFound700",
    name: "700个远古道具被找到",
    requirementType: 22,
    requiredCount: 700,
    pointEventTypeId: 10
  }, {
    id: "ancientItemsFound800",
    name: "800个远古道具被找到",
    requirementType: 22,
    requiredCount: 800,
    pointEventTypeId: 9
  }, {
    id: "reducedPartyVictory1",
    name: "使用1个冒险者获得胜利",
    requirementType: 23,
    requiredCount: 1,
    pointEventTypeId: POINT_EVENT_LEVEL_CLEARED,
    isVictoryAchievement: true
  }, {
    id: "reducedPartyVictory2",
    name: "使用2个冒险者获得胜利",
    requirementType: 23,
    requiredCount: 2,
    pointEventTypeId: 19,
    isVictoryAchievement: true
  }, {
    id: "reducedPartyVictory3",
    name: "使用3个冒险者获得胜利",
    requirementType: 23,
    requiredCount: 3,
    pointEventTypeId: 21,
    isVictoryAchievement: true
  }, {
    id: "singleClassVictory",
    name: "使用4个同职业冒险者获得胜利",
    requirementType: 24,
    requiredCount: 1,
    pointEventTypeId: 22,
    isVictoryAchievement: true
  }, {
    id: "barbarianVictory",
    name: "使用野蛮人获得胜利",
    requirementType: 25,
    Hb: 1,
    requiredCount: 1,
    pointEventTypeId: 16,
    isVictoryAchievement: true
  }, {
    id: "fighterVictory",
    name: "使用战士获得胜利",
    requirementType: 25,
    Hb: 0,
    requiredCount: 1,
    pointEventTypeId: 15,
    isVictoryAchievement: true
  }, {
    id: "priestVictory",
    name: "使用牧师获得胜利",
    requirementType: 25,
    Hb: 6,
    requiredCount: 1,
    pointEventTypeId: 14,
    isVictoryAchievement: true
  }, {
    id: "rangerVictory",
    name: "使用游侠获得胜利",
    requirementType: 25,
    Hb: 2,
    requiredCount: 1,
    pointEventTypeId: 13,
    isVictoryAchievement: true
  }, {
    id: "druidVictory",
    name: "使用德鲁伊获得胜利",
    requirementType: 25,
    Hb: 10,
    requiredCount: 1,
    pointEventTypeId: 8,
    isVictoryAchievement: true
  }, {
    id: "rogueVictory",
    name: "使用盗贼获得胜利",
    requirementType: 25,
    Hb: 7,
    requiredCount: 1,
    pointEventTypeId: 6,
    isVictoryAchievement: true
  }, {
    id: "pyromancerVictory",
    name: "使用火法师获得胜利",
    requirementType: 25,
    Hb: 4,
    requiredCount: 1,
    pointEventTypeId: 7,
    isVictoryAchievement: true
  }, {
    id: "electromancerVictory",
    name: "使用电法师获得胜利",
    requirementType: 25,
    Hb: 3,
    requiredCount: 1,
    pointEventTypeId: 12,
    isVictoryAchievement: true
  }, {
    id: "necromancerVictory",
    name: "使用死灵法师获得胜利",
    requirementType: 25,
    Hb: 9,
    requiredCount: 1,
    pointEventTypeId: 11,
    isVictoryAchievement: true
  }, {
    id: "chickenKingVictory",
    name: "使用鸡王获得胜利",
    requirementType: 25,
    Hb: 11,
    requiredCount: 1,
    pointEventTypeId: 9,
    isVictoryAchievement: true
  }, {
    id: "ninjaVictory",
    name: "使用忍者获得胜利",
    requirementType: 25,
    Hb: 8,
    requiredCount: 1,
    pointEventTypeId: 2,
    isVictoryAchievement: true
  }, {
    id: "continuationVictory1",
    name: "延续胜利",
    requirementType: 26,
    requiredCount: 1,
    pointEventTypeId: 10,
    isVictoryAchievement: true
  }, {
    id: "continuationVictory2",
    name: "第二次延续胜利",
    requirementType: 26,
    requiredCount: 2,
    pointEventTypeId: POINT_EVENT_LEVEL_CLEARED,
    isVictoryAchievement: true
  }, {
    id: "continuationVictory3",
    name: "第三次延续胜利",
    requirementType: 26,
    requiredCount: 3,
    pointEventTypeId: 22,
    isVictoryAchievement: true
  }, {
    id: "continuationVictory4",
    name: "第四次延续胜利",
    requirementType: 26,
    requiredCount: 4,
    pointEventTypeId: 2,
    isVictoryAchievement: true
  }, {
    id: "soloBarbarianVictory",
    name: "单独使用野蛮人获得胜利",
    requirementType: 27,
    Hb: 1,
    requiredCount: 1,
    pointEventTypeId: 22,
    isVictoryAchievement: true
  }, {
    id: "soloFighterVictory",
    name: "单独使用战士获得胜利",
    requirementType: 27,
    Hb: 0,
    requiredCount: 1,
    pointEventTypeId: 1,
    isVictoryAchievement: true
  }, {
    id: "soloPriestVictory",
    name: "单独使用牧师获得胜利",
    requirementType: 27,
    Hb: 6,
    requiredCount: 1,
    pointEventTypeId: 13,
    isVictoryAchievement: true
  }, {
    id: "soloRangerVictory",
    name: "单独使用游侠获得胜利",
    requirementType: 27,
    Hb: 2,
    requiredCount: 1,
    pointEventTypeId: 14,
    isVictoryAchievement: true
  }, {
    id: "soloDruidVictory",
    name: "单独使用德鲁伊获得胜利",
    requirementType: 27,
    Hb: 10,
    requiredCount: 1,
    pointEventTypeId: 15,
    isVictoryAchievement: true
  }, {
    id: "soloRogueVictory",
    name: "单独使用盗贼获得胜利",
    requirementType: 27,
    Hb: 7,
    requiredCount: 1,
    pointEventTypeId: 16,
    isVictoryAchievement: true
  }, {
    id: "soloPyromancerVictory",
    name: "单独使用火法师获得胜利",
    requirementType: 27,
    Hb: 4,
    requiredCount: 1,
    pointEventTypeId: 21,
    isVictoryAchievement: true
  }, {
    id: "soloElectromancerVictory",
    name: "单独使用电法师获得胜利",
    requirementType: 27,
    Hb: 3,
    requiredCount: 1,
    pointEventTypeId: POINT_EVENT_DUNGEON_CLEARED,
    isVictoryAchievement: true
  }, {
    id: "soloNecromancerVictory",
    name: "单独使用死灵法师获得胜利",
    requirementType: 27,
    Hb: 9,
    requiredCount: 1,
    pointEventTypeId: 19,
    isVictoryAchievement: true
  }, {
    id: "soloChickenKingVictory",
    name: "单独使用鸡王获得胜利",
    requirementType: 27,
    Hb: 11,
    requiredCount: 1,
    pointEventTypeId: POINT_EVENT_LEVEL_CLEARED,
    isVictoryAchievement: true
  }, {
    id: "soloNinjaVictory",
    name: "单独使用忍者获得胜利",
    requirementType: 27,
    Hb: 8,
    requiredCount: 1,
    pointEventTypeId: 17,
    isVictoryAchievement: true
  }];
}
