import { initializeContentAnimations } from '../content/animations.js';
import { initializeContentMonsters } from '../content/monsters.js';
import { initializeCoreBootstrapData } from '../core/bootstrap-data.js';
import { initializeContentEquipment } from '../content/equipment.js';
import { initializeWorldInitialization } from '../world/initialization.js';
import { initializeCoreMath } from '../core/math.js';
import { initializeRenderingSprites } from '../rendering/sprites.js';
import { initializeWorldRegions } from '../world/regions.js';
import { initializeWorldDungeons } from '../world/dungeons.js';
import { initializeWorldTerrain } from '../world/terrain.js';
import { initializeContentDungeonThemes } from '../content/dungeon-themes.js';
import { initializeWorldRooms } from '../world/rooms.js';
import { initializeWorldPathfinding } from '../world/pathfinding.js';
import { initializeWorldGeneration } from '../world/generation.js';
import { initializeRenderingFloatingText } from '../rendering/floating-text.js';
import { initializeCombatEncounters } from '../combat/encounters.js';
import { initializeLootTreasure } from '../loot/treasure.js';
import { initializeCombatSkillEffects } from '../combat/skill-effects.js';
import { initializeContentSkillsBarbarian } from '../content/skills/barbarian.js';
import { initializeContentSkillsFighter } from '../content/skills/fighter.js';
import { initializeContentSkillsNinja } from '../content/skills/ninja.js';
import { initializeContentSkillsPriest } from '../content/skills/priest.js';
import { initializeContentSkillsElectromancer } from '../content/skills/electromancer.js';
import { initializeContentSkillsPyromancer } from '../content/skills/pyromancer.js';
import { initializeContentSkillsRanger } from '../content/skills/ranger.js';
import { initializeContentSkillsRogue } from '../content/skills/rogue.js';
import { initializeContentSkillsNecromancer } from '../content/skills/necromancer.js';
import { initializeContentSkillsDruid } from '../content/skills/druid.js';
import { initializeContentSkillsChickenKing } from '../content/skills/chicken-king.js';
import { initializeContentSpells } from '../content/spells.js';
import { initializeCombatScrolls } from '../combat/scrolls.js';
import { initializeCombatPotions } from '../combat/potions.js';
import { initializeProgressionPoints } from '../progression/points.js';
import { initializeProgressionAchievements } from '../progression/achievements.js';
import { initializeProgressionUpgrades } from '../progression/upgrades.js';
import { initializeAiTargeting } from '../ai/targeting.js';
import { initializeAiBehaviors } from '../ai/behaviors.js';
import { initializeContentClasses } from '../content/classes.js';
import { initializeContentMinions } from '../content/minions.js';
import { initializeCharactersMinions } from '../characters/minions.js';
import { initializeContentGuardians } from '../content/guardians.js';
import { initializeLootItemNames } from '../loot/item-names.js';
import { initializeLootItems } from '../loot/items.js';
import { initializeLootInventory } from '../loot/inventory.js';
import { initializeCombatActions } from '../combat/actions.js';
import { initializeCharactersStats } from '../characters/stats.js';
import { initializeCharactersEffects } from '../characters/effects.js';
import { initializeCharactersMovement } from '../characters/movement.js';
import { initializeCharactersCharacter } from '../characters/character.js';
import { initializeWorldTravelCosts } from '../world/travel-costs.js';
import { initializeProgressionStatistics } from '../progression/statistics.js';
import { initializeCharactersParty } from '../characters/party.js';
import { initializeContentBalance } from '../content/balance.js';
import { initializeViewsDom } from '../views/dom.js';
import { initializeViewsBase } from '../views/base.js';
import { initializeViewsNavigation } from '../views/navigation.js';
import { initializeViewsUpgradeDetails } from '../views/upgrade-details.js';
import { initializeRenderingScene } from '../rendering/scene.js';
import { initializeViewsExpedition } from '../views/expedition.js';
import { initializeViewsInformation } from '../views/information.js';
import { initializeViewsPartyCreation } from '../views/party-creation.js';
import { initializeViewsCharacter } from '../views/character.js';
import { initializeViewsMonsters } from '../views/monsters.js';
import { initializeViewsCastles } from '../views/castles.js';
import { initializeViewsResources } from '../views/resources.js';
import { initializeViewsDungeons } from '../views/dungeons.js';
import { initializeViewsResults } from '../views/results.js';
import { initializeViewsAchievements } from '../views/achievements.js';
import { initializePersistenceEntities } from '../persistence/entities.js';
import { initializePersistenceGameSave } from '../persistence/game-save.js';
import { initializeSimulationCharacters } from '../simulation/characters.js';
import { initializeSimulationTick } from '../simulation/tick.js';
import { initializeSimulationLoop } from '../simulation/loop.js';
import { initializeRuntimeGame } from './game.js';

// 模块初始化阶段只有这里拥有调用顺序；函数提升和原版初始值保持一致。
initializeContentAnimations();
initializeContentMonsters();
initializeCoreBootstrapData();
initializeContentEquipment();
initializeWorldInitialization();
initializeCoreMath();
initializeRenderingSprites();
initializeWorldRegions();
initializeWorldDungeons();
initializeWorldTerrain();
initializeContentDungeonThemes();
initializeWorldRooms();
initializeWorldPathfinding();
initializeWorldGeneration();
initializeRenderingFloatingText();
initializeCombatEncounters();
initializeLootTreasure();
initializeCombatSkillEffects();
initializeContentSkillsBarbarian();
initializeContentSkillsFighter();
initializeContentSkillsNinja();
initializeContentSkillsPriest();
initializeContentSkillsElectromancer();
initializeContentSkillsPyromancer();
initializeContentSkillsRanger();
initializeContentSkillsRogue();
initializeContentSkillsNecromancer();
initializeContentSkillsDruid();
initializeContentSkillsChickenKing();
initializeContentSpells();
initializeCombatScrolls();
initializeCombatPotions();
initializeProgressionPoints();
initializeProgressionAchievements();
initializeProgressionUpgrades();
initializeAiTargeting();
initializeAiBehaviors();
initializeContentClasses();
initializeContentMinions();
initializeCharactersMinions();
initializeContentGuardians();
initializeLootItemNames();
initializeLootItems();
initializeLootInventory();
initializeCombatActions();
initializeCharactersStats();
initializeCharactersEffects();
initializeCharactersMovement();
initializeCharactersCharacter();
initializeWorldTravelCosts();
initializeProgressionStatistics();
initializeCharactersParty();
initializeContentBalance();
initializeViewsDom();
initializeViewsBase();
initializeViewsNavigation();
initializeViewsUpgradeDetails();
initializeRenderingScene();
initializeViewsExpedition();
initializeViewsInformation();
initializeViewsPartyCreation();
initializeViewsCharacter();
initializeViewsMonsters();
initializeViewsCastles();
initializeViewsResources();
initializeViewsDungeons();
initializeViewsResults();
initializeViewsAchievements();
initializePersistenceEntities();
initializePersistenceGameSave();
initializeSimulationCharacters();
initializeSimulationTick();
initializeSimulationLoop();
initializeRuntimeGame();
export { game } from './game.js';
