// @ts-nocheck -- M10 渐进类型化：JSDoc 覆盖后摘除（见 docs/WORKSTATE.md）
/** 从原始组合根独立出的配置数据。
 * 初始化由 runtime/index.js 统一协调；字段与原符号映射见 docs/symbol-map.json。
 */
export var monsterDefinitions;
export function initializeContentMonsters() {
  monsterDefinitions = [{
    name: "棕色蝙蝠",
    spriteName: "RatBrownDark.PNG"
  }, {
    name: "灰色蝙蝠",
    spriteName: "RatGrey.PNG"
  }, {
    name: "实验蝙蝠",
    spriteName: "RatWhite.PNG"
  }, {
    name: "绿色蜻蜓",
    spriteName: "DragonFlyGreen.PNG"
  }, {
    name: "粉色蜻蜓",
    spriteName: "DragonFlyPink.PNG"
  }, {
    name: "橙色蜻蜓",
    spriteName: "DragonFlyOrange.PNG"
  }, {
    name: "黑色蜻蜓",
    spriteName: "DragonFlyBlack.PNG"
  }, {
    name: "白色蜻蜓",
    spriteName: "DragonFlyWhite.PNG"
  }, {
    name: "棕色蝙蝠",
    spriteName: "BatBrown.PNG"
  }, {
    name: "蓝色蝙蝠",
    spriteName: "BatBlueTail.PNG"
  }, {
    name: "灰色蝙蝠",
    spriteName: "BatGrey.PNG"
  }, {
    name: "红色蝙蝠",
    spriteName: "BatRedTail.PNG"
  }, {
    name: "银色蝙蝠",
    spriteName: "BatSilver.PNG"
  }, {
    name: "蓝色蜈蚣",
    spriteName: "CentipedeBlue.PNG"
  }, {
    name: "粉色蜈蚣",
    spriteName: "CentipedePink.PNG"
  }, {
    name: "棕色蜈蚣",
    spriteName: "CentipedeBrown.PNG"
  }, {
    name: "灰色蜈蚣",
    spriteName: "CentipedeGrey.PNG"
  }, {
    name: "银色蜈蚣",
    spriteName: "CentipedeSilver.PNG"
  }, {
    name: "猩红蜈蚣",
    spriteName: "CentipedeRed.PNG"
  }, {
    name: "棕色蜥蜴",
    spriteName: "LizardBrown.PNG"
  }, {
    name: "绿色蜥蜴",
    spriteName: "LizardGreen.PNG"
  }, {
    name: "灰色蜥蜴",
    spriteName: "LizardGrey.PNG"
  }, {
    name: "红色蜥蜴",
    spriteName: "LizardRed.PNG"
  }, {
    name: "条纹蜥蜴",
    spriteName: "LizardStriped.PNG"
  }, {
    name: "苍白爬行者",
    spriteName: "CrawlerWhite.PNG"
  }, {
    name: "浅绿爬行者",
    spriteName: "CrawlerBlueLight.PNG"
  }, {
    name: "蓝色爬行者",
    spriteName: "CrawlerBlue.PNG"
  }, {
    name: "绿色爬行者",
    spriteName: "CrawlerGreen.PNG"
  }, {
    name: "灰色爬行者",
    spriteName: "CrawlerGrey.PNG"
  }, {
    name: "橙色爬行者",
    spriteName: "CrawlerOrange.PNG"
  }, {
    name: "银色爬行者",
    spriteName: "CrawlerSilver.PNG"
  }, {
    name: "红色爬行者",
    spriteName: "CrawlerRed.PNG"
  }, {
    name: "棕色狗狗",
    spriteName: "DogBrown.PNG"
  }, {
    name: "橙色狗狗",
    spriteName: "DogOrange.PNG"
  }, {
    name: "灰色狗狗",
    spriteName: "DogGrey.PNG"
  }, {
    name: "苍白狗狗",
    spriteName: "DogWhite.PNG"
  }, {
    name: "阴影狗狗",
    spriteName: "DogDarkGrey.PNG"
  }, {
    name: "粉色狗狗",
    spriteName: "DogPink.PNG"
  }, {
    name: "蓝色蜘蛛",
    spriteName: "SpiderBlue.PNG"
  }, {
    name: "黄金蜘蛛",
    spriteName: "SpiderGold.PNG"
  }, {
    name: "绿色蜘蛛",
    spriteName: "SpiderGreen.PNG"
  }, {
    name: "紫色蜘蛛",
    spriteName: "SpiderPurple.PNG"
  }, {
    name: "红色蜘蛛",
    spriteName: "SpiderRed.PNG"
  }, {
    name: "黑色蜘蛛",
    spriteName: "SpiderBlack.PNG"
  }, {
    name: "巨型粉色青蛙",
    spriteName: "FrogGiantPink.PNG"
  }, {
    name: "巨型绿色青蛙",
    spriteName: "FrogGiantGreen.PNG"
  }, {
    name: "棕色巨蛇",
    spriteName: "SnakeBrown.PNG"
  }, {
    name: "蓝色巨蛇",
    spriteName: "SnakeBlue.PNG"
  }, {
    name: "绿色巨蛇",
    spriteName: "SnakeGreen.PNG"
  }, {
    name: "灰色巨蛇",
    spriteName: "SnakeGrey.PNG"
  }, {
    name: "粉色巨蛇",
    spriteName: "SnakePink.PNG"
  }, {
    name: "银色巨蛇",
    spriteName: "SnakeSilver.PNG"
  }, {
    name: "白色巨蛇",
    spriteName: "SnakeWhite2.PNG"
  }, {
    name: "棕色活泥",
    spriteName: "LivingMoundBrown.PNG"
  }, {
    name: "斑点活泥",
    spriteName: "LivingMoundBrownGreen.PNG"
  }, {
    name: "肉体活泥",
    spriteName: "LivingMoundFlesh.PNG"
  }, {
    name: "绿色活泥",
    spriteName: "LivingMoundGreen.PNG"
  }, {
    name: "品红活泥",
    spriteName: "LivingMoundMagenta.PNG"
  }, {
    name: "橙色活泥",
    spriteName: "LivingMoundOrange.PNG"
  }, {
    name: "红色活泥",
    spriteName: "LivingMoundRed.PNG"
  }, {
    name: "棕色乌龟",
    spriteName: "TurtleBrown.PNG"
  }, {
    name: "蓝色乌龟",
    spriteName: "TurtleBlue.PNG"
  }, {
    name: "绿色乌龟",
    spriteName: "TurtleGreen.PNG"
  }, {
    name: "粉色乌龟",
    spriteName: "TurtlePink.PNG"
  }, {
    name: "黄色乌龟",
    spriteName: "TurtleYellow.PNG"
  }, {
    name: "灰色乌龟",
    spriteName: "TurtleGrey.PNG"
  }, {
    name: "灰色幽灵",
    spriteName: "Ghost3Grey.PNG"
  }, {
    name: "粉色幽灵",
    spriteName: "Ghost3Pink.PNG"
  }, {
    name: "蓝色幽灵",
    spriteName: "Ghost3Blue.PNG"
  }, {
    name: "绿色幽灵",
    spriteName: "GhostGreen.PNG"
  }, {
    name: "红色幽灵",
    spriteName: "GhostRed.PNG"
  }, {
    name: "黑色幽灵",
    spriteName: "GhostBlack.PNG"
  }, {
    name: "蓝色浮眼",
    spriteName: "FloatingEyeBlue.PNG"
  }, {
    name: "绿色浮眼",
    spriteName: "FloatingEyeGreen.PNG"
  }, {
    name: "灰色浮眼",
    spriteName: "FloatingEyeGrey.PNG"
  }, {
    name: "红色浮眼",
    spriteName: "FloatingEyeRed.PNG"
  }, {
    name: "触手浮眼",
    spriteName: "FloatingEyeTentacled3Eyes.PNG"
  }, {
    name: "成熟浮眼",
    spriteName: "FloatingEyeTentacled6Eyes.PNG"
  }, {
    name: "青色水母",
    spriteName: "JellyfishTeal.PNG"
  }, {
    name: "蓝色水母",
    spriteName: "JellyfishBlue.PNG"
  }, {
    name: "棕色水母",
    spriteName: "JellyfishBrown.PNG"
  }, {
    name: "绿色水母",
    spriteName: "JellyfishGreen.PNG"
  }, {
    name: "灰色水母",
    spriteName: "JellyfishGrey.PNG"
  }, {
    name: "橙色水母",
    spriteName: "JellyfishOrange.PNG"
  }, {
    name: "粉色水母",
    spriteName: "JellyfishPink.PNG"
  }, {
    name: "红色水母",
    spriteName: "JellyfishRed.PNG"
  }, {
    name: "白色水母",
    spriteName: "JellyfishWhite2.PNG"
  }, {
    name: "黄色水母",
    spriteName: "JellyfishYellow.PNG"
  }, {
    name: "棕色霉菌",
    spriteName: "MoldBrown.PNG"
  }, {
    name: "蓝色霉菌",
    spriteName: "MoldBlue.PNG"
  }, {
    name: "灰色霉菌",
    spriteName: "MoldBlueGrey.PNG"
  }, {
    name: "绿色霉菌",
    spriteName: "MoldGreen.PNG"
  }, {
    name: "紫色霉菌",
    spriteName: "MoldPurple.PNG"
  }, {
    name: "红色霉菌",
    spriteName: "MoldRed.PNG"
  }, {
    name: "棕色眼镜蛇",
    spriteName: "SnakeCobraBrown.PNG"
  }, {
    name: "绿色眼镜蛇",
    spriteName: "SnakeCobraGreen.PNG"
  }, {
    name: "灰色眼镜蛇",
    spriteName: "SnakeCobraGrey.PNG"
  }, {
    name: "红色眼镜蛇",
    spriteName: "SnakeCobraRed.PNG"
  }, {
    name: "蓝色雪人",
    spriteName: "YetiBlue.PNG"
  }, {
    name: "棕色雪人",
    spriteName: "YetiBrown.PNG"
  }, {
    name: "绿色雪人",
    spriteName: "YetiGreen.PNG"
  }, {
    name: "浅绿雪人",
    spriteName: "YetiGreenBlue.PNG"
  }, {
    name: "灰色雪人",
    spriteName: "YetiGreyDark.PNG"
  }, {
    name: "橙色雪人",
    spriteName: "YetiOrange.PNG"
  }, {
    name: "粉色雪人",
    spriteName: "YetiPink.PNG"
  }, {
    name: "黑色雪人",
    spriteName: "YetiBlack.PNG"
  }, {
    name: "幼年蓝龙",
    spriteName: "DragonBabyBlue.PNG"
  }, {
    name: "幼年青铜龙",
    spriteName: "DragonBabyBronze.PNG"
  }, {
    name: "幼年黄金龙",
    spriteName: "DragonBabyGold.PNG"
  }, {
    name: "幼年绿龙",
    spriteName: "DragonBabyGreen.PNG"
  }, {
    name: "幼年彩虹龙",
    spriteName: "DragonBabyRainbow.PNG"
  }, {
    name: "幼年银龙",
    spriteName: "DragonBabySilver.PNG"
  }, {
    name: "幼年红龙",
    spriteName: "DragonBabyRed.PNG"
  }, {
    name: "幼年黑龙",
    spriteName: "DragonBabyBlack.PNG"
  }, {
    name: "蓝色龙人",
    spriteName: "DragonManBlue.PNG"
  }, {
    name: "青铜龙人",
    spriteName: "DragonManBronze.PNG"
  }, {
    name: "黄金龙人",
    spriteName: "DragonManGold.PNG"
  }, {
    name: "绿色龙人",
    spriteName: "DragonManGreen.PNG"
  }, {
    name: "彩虹龙人",
    spriteName: "DragonManRainbow.PNG"
  }, {
    name: "银色龙人",
    spriteName: "DragonManSilver.PNG"
  }, {
    name: "红色龙人",
    spriteName: "DragonManRed.PNG"
  }, {
    name: "黑色龙人",
    spriteName: "DragonManBlack.PNG"
  }, {
    name: "粉色木乃伊",
    spriteName: "MummyPink.PNG"
  }, {
    name: "绿色木乃伊",
    spriteName: "MummyGreen.PNG"
  }, {
    name: "灰色木乃伊",
    spriteName: "MummyGrey.PNG"
  }, {
    name: "紫色木乃伊",
    spriteName: "MummyPurple.PNG"
  }, {
    name: "红色木乃伊",
    spriteName: "MummyRed.PNG"
  }, {
    name: "青色木乃伊",
    spriteName: "MummyTeal.PNG"
  }, {
    name: "白色木乃伊",
    spriteName: "MummyWhite.PNG"
  }, {
    name: "黑色木乃伊",
    spriteName: "MummyYellow.PNG"
  }, {
    name: "棕色蝎子",
    spriteName: "ScorpionBrown.PNG"
  }, {
    name: "蓝色蝎子",
    spriteName: "ScorpionBlue.PNG"
  }, {
    name: "灰色蝎子",
    spriteName: "ScorpionGrey.PNG"
  }, {
    name: "粉色蝎子",
    spriteName: "ScorpionPink.PNG"
  }, {
    name: "绿色蝎子",
    spriteName: "ScorpionGreenYellow.PNG"
  }, {
    name: "黑色蝎子",
    spriteName: "ScorpionBlack.PNG"
  }, {
    name: "粉色恐龙",
    spriteName: "DinosaurBeastGiantPink.PNG"
  }, {
    name: "棕色恐龙",
    spriteName: "DinosaurBeastGiantBrown.PNG"
  }, {
    name: "黄色恐龙",
    spriteName: "DinosaurBeastGiantYellow.PNG"
  }, {
    name: "绿色恐龙",
    spriteName: "DinosaurBeastGiantGreen.PNG"
  }, {
    name: "灰色恐龙",
    spriteName: "DinosaurBeastGiantGrey.PNG"
  }, {
    name: "红色恐龙",
    spriteName: "DinosaurBeastGiantRed.PNG"
  }, {
    name: "青年蓝龙",
    spriteName: "DragonYoungBlue.PNG"
  }, {
    name: "青年青铜龙",
    spriteName: "DragonYoungBronze.PNG"
  }, {
    name: "青年黄金龙",
    spriteName: "DragonYoungGold.PNG"
  }, {
    name: "青年绿龙",
    spriteName: "DragonYoungGreen.PNG"
  }, {
    name: "青年彩虹龙",
    spriteName: "DragonYoungRainbow.PNG"
  }, {
    name: "青年银龙",
    spriteName: "DragonYoungSilver.PNG"
  }, {
    name: "青年红龙",
    spriteName: "DragonYoungRed.PNG"
  }, {
    name: "青年黑龙",
    spriteName: "DragonYoungBlack.PNG"
  }, {
    name: "黑色巨熊",
    spriteName: "BlackBear.PNG"
  }, {
    name: "棕色巨熊",
    spriteName: "BrownBear.PNG"
  }, {
    name: "灰色巨熊",
    spriteName: "GrizzlyBear.PNG"
  }, {
    name: "气元素",
    spriteName: "ElementalAir.PNG"
  }, {
    name: "水元素",
    spriteName: "ElementalWater.PNG"
  }, {
    name: "土元素",
    spriteName: "ElementalEarth.PNG"
  }, {
    name: "石元素",
    spriteName: "ElementalStone.PNG"
  }, {
    name: "火元素",
    spriteName: "ElementalFire.PNG"
  }, {
    name: "虚空元素",
    spriteName: "ElementalVoid.PNG"
  }, {
    name: "僵尸",
    spriteName: "Zombie.PNG"
  }, {
    name: "蓝色僵尸",
    spriteName: "ZombieBlue.PNG"
  }, {
    name: "红色僵尸",
    spriteName: "ZombieRed.PNG"
  }, {
    name: "水妖精",
    spriteName: "SpriteWater.PNG"
  }, {
    name: "火妖精",
    spriteName: "SpriteFire.PNG"
  }, {
    name: "棕色天使",
    spriteName: "AngelBrown.PNG"
  }, {
    name: "紫色天使",
    spriteName: "AngelPurple.PNG"
  }, {
    name: "蓝色天使",
    spriteName: "AngelBlue.PNG"
  }, {
    name: "橙色天使",
    spriteName: "AngelOrange.PNG"
  }, {
    name: "灰色天使",
    spriteName: "AngelGrey.PNG"
  }, {
    name: "银色天使",
    spriteName: "AngelSilver.PNG"
  }, {
    name: "猩红天使",
    spriteName: "AngelRed.PNG"
  }, {
    name: "暗黑天使",
    spriteName: "AngelGrey2.PNG"
  }, {
    name: "棕色鹰犬",
    spriteName: "EagleHoundBrown.PNG"
  }, {
    name: "蓝色鹰犬",
    spriteName: "EagleHoundBlue.PNG"
  }, {
    name: "黄金鹰犬",
    spriteName: "EagleHoundGold.PNG"
  }, {
    name: "绿色鹰犬",
    spriteName: "EagleHoundGreenDark.PNG"
  }, {
    name: "灰色鹰犬",
    spriteName: "EagleHoundGrey.PNG"
  }, {
    name: "暗黑鹰犬",
    spriteName: "EagleHoundGrey2.PNG"
  }, {
    name: "黑色鹰犬",
    spriteName: "EagleHoundBlack.PNG"
  }, {
    name: "棕色两头蛇",
    spriteName: "Hydra2HeadBrown.PNG"
  }, {
    name: "红色三头蛇",
    spriteName: "Hydra3HeadRed.PNG"
  }, {
    name: "灰色四头蛇",
    spriteName: "Hydra4HeadGrey.PNG"
  }, {
    name: "白色五头蛇",
    spriteName: "Hydra5EyedWhite.PNG"
  }, {
    name: "黄色六头蛇",
    spriteName: "Hydra6HeadYellow.PNG"
  }, {
    name: "灰色七头蛇",
    spriteName: "Hydra7HeadGrey.PNG"
  }, {
    name: "紫色八头蛇",
    spriteName: "Hydra8HeadPurple.PNG"
  }, {
    name: "绿色九头蛇",
    spriteName: "Hydra9HeadedGreen.PNG"
  }, {
    name: "红色十头蛇",
    spriteName: "Hydra10HeadRed.PNG"
  }, {
    name: "郊区居民",
    spriteName: "People01.PNG"
  }, {
    name: "八旬老人",
    spriteName: "People02.PNG"
  }, {
    name: "百岁老人",
    spriteName: "People03.PNG"
  }, {
    name: "农民",
    spriteName: "PeopleFarmer.PNG"
  }, {
    name: "驼背",
    spriteName: "PeopleHunchback.PNG"
  }, {
    name: "粉色死亡蠕虫",
    spriteName: "WormMassPinkGrey.PNG"
  }, {
    name: "蓝色死亡蠕虫",
    spriteName: "WormMassBlue.PNG"
  }, {
    name: "绿色死亡蠕虫",
    spriteName: "WormMassGreen.PNG"
  }, {
    name: "灰色死亡蠕虫",
    spriteName: "WormMassGrey.PNG"
  }, {
    name: "红色死亡蠕虫",
    spriteName: "WormMassRedPink.PNG"
  }, {
    name: "青色死亡蠕虫",
    spriteName: "WormMassTeal.PNG"
  }, {
    name: "黄色死亡蠕虫",
    spriteName: "WormMassYellow.PNG"
  }, {
    name: "蓝色鬼魂",
    spriteName: "WraithBlue.PNG"
  }, {
    name: "绿色鬼魂",
    spriteName: "WraithGreen.PNG"
  }, {
    name: "灰色鬼魂",
    spriteName: "WraithGrey.PNG"
  }, {
    name: "橙色鬼魂",
    spriteName: "WraithOrange.PNG"
  }, {
    name: "紫色鬼魂",
    spriteName: "WraithPurple.PNG"
  }, {
    name: "红色鬼魂",
    spriteName: "WraithRed.PNG"
  }, {
    name: "鬼魂领主",
    spriteName: "WraithLord.PNG"
  }, {
    name: "鬼魂国王",
    spriteName: "WraithKing.PNG"
  }, {
    name: "棕色软泥",
    spriteName: "OozeBrown.PNG"
  }, {
    name: "蓝色软泥",
    spriteName: "OozeBlue.PNG"
  }, {
    name: "绿色软泥",
    spriteName: "OozeGreen.PNG"
  }, {
    name: "灰色软泥",
    spriteName: "OozeGrey.PNG"
  }, {
    name: "黑色软泥",
    spriteName: "OozeBlack.PNG"
  }, {
    name: "棕色蛇怪",
    spriteName: "BasiliskBrown.PNG"
  }, {
    name: "绿色蛇怪",
    spriteName: "BasiliskGreen.PNG"
  }, {
    name: "银色蛇怪",
    spriteName: "BasiliskSilver.PNG"
  }, {
    name: "猩红蛇怪",
    spriteName: "BasiliskRed.PNG"
  }, {
    name: "蓝龙",
    spriteName: "DragonAdultBlue.PNG"
  }, {
    name: "青铜龙",
    spriteName: "DragonAdultBronze.PNG"
  }, {
    name: "黄金龙",
    spriteName: "DragonAdultGold.PNG"
  }, {
    name: "绿龙",
    spriteName: "DragonAdultGreen.PNG"
  }, {
    name: "彩虹龙",
    spriteName: "DragonAdultRainbow.PNG"
  }, {
    name: "银龙",
    spriteName: "DragonAdultSilver.PNG"
  }, {
    name: "红龙",
    spriteName: "DragonAdultRed.PNG"
  }, {
    name: "黑龙",
    spriteName: "DragonAdultBlack.PNG"
  }, {
    name: "骷髅",
    spriteName: "Skeleton.PNG"
  }, {
    name: "骷髅盗贼",
    spriteName: "SkeletonFighter.PNG"
  }, {
    name: "骷髅恶魔",
    spriteName: "SkeletonDemon.PNG"
  }, {
    name: "骷髅战士",
    spriteName: "SkeletonFighter3.PNG"
  }, {
    name: "骷髅野蛮人",
    spriteName: "SkeletonFighter13.PNG"
  }, {
    name: "骷髅刀锋战士",
    spriteName: "SkeletonFighter6.PNG"
  }, {
    name: "骷髅恶魔战士",
    spriteName: "SkeletonDemonFighter.PNG"
  }, {
    name: "绿色精灵",
    spriteName: "SpiritGreen.PNG"
  }, {
    name: "棕色精灵",
    spriteName: "SpiritBrown.PNG"
  }, {
    name: "土精灵",
    spriteName: "SpiritEarth.PNG"
  }, {
    name: "气精灵",
    spriteName: "SpiritAir.PNG"
  }, {
    name: "暗黑精灵",
    spriteName: "SpiritGreyDark.PNG"
  }, {
    name: "火精灵",
    spriteName: "SpiritFire.PNG"
  }, {
    name: "初拥吸血鬼",
    spriteName: "Vampire2.PNG"
  }, {
    name: "吸血鬼",
    spriteName: "Vampire3.PNG"
  }, {
    name: "长老吸血鬼",
    spriteName: "Vampire4.PNG"
  }, {
    name: "远古吸血鬼",
    spriteName: "VampireMage1.PNG"
  }, {
    name: "远古蓝龙",
    spriteName: "DragonAncientBlue.PNG"
  }, {
    name: "远古青铜龙",
    spriteName: "DragonAncientBronze.PNG"
  }, {
    name: "远古黄金龙",
    spriteName: "DragonAncientGold.PNG"
  }, {
    name: "远古白龙",
    spriteName: "DragonAncientGoldWhite.PNG"
  }, {
    name: "远古绿龙",
    spriteName: "DragonAncientGreen.PNG"
  }, {
    name: "远古彩虹龙",
    spriteName: "DragonAncientRainbow.PNG"
  }, {
    name: "远古银龙",
    spriteName: "DragonAncientSilver.PNG"
  }, {
    name: "远古红龙",
    spriteName: "DragonAncientRed.PNG"
  }, {
    name: "远古黑龙",
    spriteName: "DragonAncientBlack.PNG"
  }, {
    name: "青色魔像",
    spriteName: "GolemTeal.PNG"
  }, {
    name: "棕色魔像",
    spriteName: "GolemBrown.PNG"
  }, {
    name: "蓝色魔像",
    spriteName: "GolemBlue.PNG"
  }, {
    name: "灰色魔像",
    spriteName: "GolemGrey.PNG"
  }, {
    name: "武装魔像",
    spriteName: "GolemBrownStick.PNG"
  }, {
    name: "魔像领主",
    spriteName: "GolemBrownCaped.PNG"
  }, {
    name: "电气魔像",
    spriteName: "GolemElectric.PNG"
  }, {
    name: "幻象之眼",
    spriteName: "PhantomEye.PNG"
  }, {
    name: "幻象之手",
    spriteName: "PhantomHand.PNG"
  }, {
    name: "幻象之骨",
    spriteName: "PhantomSkull.PNG"
  }, {
    name: "蓝色鬼怪",
    spriteName: "SpectreBlue.PNG"
  }, {
    name: "绿色鬼怪",
    spriteName: "SpectreGreen.PNG"
  }, {
    name: "橙色鬼怪",
    spriteName: "SpectreOrange.PNG"
  }, {
    name: "紫色鬼怪",
    spriteName: "SpectrePurple.PNG"
  }, {
    name: "银色鬼怪",
    spriteName: "SpectreSilver.PNG"
  }, {
    name: "红色鬼怪",
    spriteName: "SpectreRed.PNG"
  }, {
    name: "黑色鬼怪",
    spriteName: "SpectreBlack.PNG"
  }, {
    name: "棕色骗子",
    spriteName: "TricksterBrown.PNG"
  }, {
    name: "蓝色骗子",
    spriteName: "TricksterBlue.PNG"
  }, {
    name: "绿色骗子",
    spriteName: "TricksterGreen.PNG"
  }, {
    name: "黑色骗子",
    spriteName: "TricksterBlack.PNG"
  }, {
    name: "红色骗子",
    spriteName: "TricksterRed.PNG"
  }, {
    name: "魔术骗子",
    spriteName: "TricksterPurpleMage.PNG"
  }, {
    name: "暗黑巨人",
    spriteName: "TrollDark.PNG"
  }, {
    name: "巨人战士",
    spriteName: "TrollFighter2.PNG"
  }, {
    name: "火巨人",
    spriteName: "TrollFire.PNG"
  }, {
    name: "石巨人",
    spriteName: "TrollGrey.PNG"
  }, {
    name: "水巨人",
    spriteName: "TrollWater.PNG"
  }, {
    name: "巨人僵尸",
    spriteName: "TrollZombie.PNG"
  }, {
    name: "巨人国王",
    spriteName: "TrollKing.PNG"
  }, {
    name: "蓝龙领主",
    spriteName: "DragonAncientLordBlue.PNG"
  }, {
    name: "青铜龙领主",
    spriteName: "DragonAncientLordBronze.PNG"
  }, {
    name: "绿龙领主",
    spriteName: "DragonAncientLordGreen.PNG"
  }, {
    name: "银龙领主",
    spriteName: "DragonAncientLordSilver.PNG"
  }, {
    name: "红龙领主",
    spriteName: "DragonAncientLordRed.PNG"
  }, {
    name: "黑龙领主",
    spriteName: "DragonAncientLordBlack.PNG"
  }, {
    name: "恶魔龙领主",
    spriteName: "DragonAncientLordSilverRed.PNG"
  }, {
    name: "巨型蓝蜉蝣",
    spriteName: "DrakeGiantBlue.PNG"
  }, {
    name: "巨型青铜蜉蝣",
    spriteName: "DrakeGiantBronze.PNG"
  }, {
    name: "巨型灰蜉蝣",
    spriteName: "DrakeGiantGrey.PNG"
  }, {
    name: "巨型白蜉蝣",
    spriteName: "DrakeGiantWhite.PNG"
  }, {
    name: "巨型红蜉蝣",
    spriteName: "DrakeGiantRed.PNG"
  }, {
    name: "巨型血蜉蝣",
    spriteName: "DrakeGiantRed2.PNG"
  }, {
    name: "巨型黑蜉蝣",
    spriteName: "DrakeGiantBlack.PNG"
  }, {
    name: "骨龙",
    spriteName: "DragonGiantBone.PNG"
  }, {
    name: "蓝色骨龙",
    spriteName: "DragonGiantBoneBlue.PNG"
  }, {
    name: "绿色骨龙",
    spriteName: "DragonGiantBoneGreen.PNG"
  }, {
    name: "灰色骨龙",
    spriteName: "DragonGiantBoneGrey.PNG"
  }, {
    name: "红色骨龙",
    spriteName: "DragonGiantBoneRed.PNG"
  }, {
    name: "冰霜巨人",
    spriteName: "GiantFrost.PNG"
  }, {
    name: "山丘巨人",
    spriteName: "GiantHill.PNG"
  }, {
    name: "风暴巨人",
    spriteName: "GiantStorm.PNG"
  }, {
    name: "双头巨人",
    spriteName: "GiantTwoHeaded.PNG"
  }, {
    name: "云层巨人",
    spriteName: "GiantCloud.PNG"
  }, {
    name: "火焰巨人",
    spriteName: "GiantFire.PNG"
  }, {
    name: "谋杀牛",
    spriteName: "CowLeft.PNG"
  }, {
    name: "噩梦小鸡",
    spriteName: "Chicken1.PNG"
  }, {
    name: "死亡小鸡",
    spriteName: "Chicken2.PNG"
  }, {
    name: "灰色骷髅领主",
    spriteName: "SkeletonFighterLord1.PNG"
  }, {
    name: "紫色骷髅领主",
    spriteName: "SkeletonFighterLord2.PNG"
  }, {
    name: "蓝色骷髅领主",
    spriteName: "SkeletonFighterLord3.PNG"
  }, {
    name: "橙色骷髅领主",
    spriteName: "SkeletonFighterLord4.PNG"
  }, {
    name: "骷髅国王",
    spriteName: "SkeletonKing.PNG"
  }];
}
